### ISSUE TITLE
Coloreado diferente en traits y derives

### ISSUE THREAD

**Issue by itroeix** [ChirujanoCodding/Casio-theme#1]
Como se debería ver:
![image](https://user-images.githubusercontent.com/54476100/229802654-2ded1cd4-007c-45a0-9c36-7a7fb1ba6dab.png)
Lo que se ve:
![image](https://user-images.githubusercontent.com/54476100/229802718-dbb572de-fac3-41a2-b958-69ebeebd9d16.png)

**Comment by romancitodev** [comment]
Luego de una investigación exhaustiva, logré identificar este "bug", lo que sucede es que estas palabras reservadas como `derive` y lo que contenga adentro, el editor lo busca por `Semantic Tokens`, y en este caso el editor se apoya sobre `rust-analyzer` para obtener el `LSP` adecuado, pero como seguramente tu IDE estaba cargando la extensión o similar, el editor se limitó a buscar por `Textmate scopes` que estos mismos se buscan mediante `Regex` y cada scope pertenece a un grupo, por lo que hay muchas palabras reservadas que comparten estos grupos, en este caso.

En este caso `derive` comparte el grupo de `meta.attribute` que tiene un background especifico para un tipo de palabras y como el IDE no lo reconoce al principio, adopta ese color, despues de comunicarse con el `rust-analyzer`, detecta que aparece como `derive` en el `Semantic Token` y sobrescribe el estilo.

Con esta conclusión determino de que no es un bug ni del theme, ni del editor.
